[[headers]]
for = "/*"

[headers.values]
  Content-Security-Policy = "base-uri 'none'; frame-ancestors 'none'; media-src 'self'; object-src 'none';"
          Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
   X-Content-Type-Options = "nosniff"
          X-Frame-Options = "DENY"
         X-XSS-Protection = "1; mode=block"
